### ISSUE TITLE
Local command to get wand on 1.21?

### ISSUE THREAD

**Issue by asyncmeow** [TheVoidBlock/litematicaWand#1]
Hello!
The NBT Editor mod recommended in the readme hasn't been ported to 1.21 yet, and it looks like it will not be ported for a while. Is it possible to add a local command in this mod to get a wand when using this on multiplayer servers?

**Comment by TheVoidBlock** [comment]
I have another mod called [voidcommands](https://modrinth.com/mod/voidcommands) that has a similar feature. After installing, you can run ```/vget litematicawand:wand``` to get the litematica wand.
